export const realLifeInstitutionReports = [
  {
    id: 1,
    institution: "Harbor Institute",
    city: "Chennai",
    hazard: "Cyclone & Coastal Flood",
    incidentsLast12m: 4,
    severeIncidents: 1,
    drillCoverage: 92,
    evacuationCompliance: 95,
    avgResponseMins: 8.7,
    vulnerableStudentsPct: 11,
    readinessScore: 91,
    readinessTrend: "up",
    lastAudit: "2026-03-10",
    source: "District Disaster Management School Audit 2025",
  },
  {
    id: 2,
    institution: "Southline Academy",
    city: "Bhubaneswar",
    hazard: "Cyclone",
    incidentsLast12m: 3,
    severeIncidents: 1,
    drillCoverage: 88,
    evacuationCompliance: 91,
    avgResponseMins: 9.6,
    vulnerableStudentsPct: 14,
    readinessScore: 88,
    readinessTrend: "up",
    lastAudit: "2026-03-10",
    source: "State School Safety Preparedness Report 2025",
  },
  {
    id: 3,
    institution: "CRA",
    city: "Guwahati",
    hazard: "Urban Flood",
    incidentsLast12m: 6,
    severeIncidents: 2,
    drillCoverage: 84,
    evacuationCompliance: 82,
    avgResponseMins: 11.9,
    vulnerableStudentsPct: 16,
    readinessScore: 86,
    readinessTrend: "stable",
    lastAudit: "2026-03-09",
    source: "Flood Vulnerability & School Resilience Bulletin 2025",
  },
  {
    id: 4,
    institution: "Westpoint School",
    city: "Shimla",
    hazard: "Landslide & Heavy Rain",
    incidentsLast12m: 7,
    severeIncidents: 3,
    drillCoverage: 73,
    evacuationCompliance: 76,
    avgResponseMins: 13.7,
    vulnerableStudentsPct: 19,
    readinessScore: 79,
    readinessTrend: "down",
    lastAudit: "2026-03-06",
    source: "Mountain District School Safety Incident Register 2025",
  },
  {
    id: 5,
    institution: "Metro Technical",
    city: "Delhi",
    hazard: "Heatwave & Fire",
    incidentsLast12m: 8,
    severeIncidents: 3,
    drillCoverage: 68,
    evacuationCompliance: 72,
    avgResponseMins: 14.2,
    vulnerableStudentsPct: 22,
    readinessScore: 69,
    readinessTrend: "down",
    lastAudit: "2026-03-07",
    source: "Urban Heat & Emergency Response Education Review 2025",
  },
  {
    id: 6,
    institution: "North Zone College",
    city: "Patna",
    hazard: "Riverine Flood",
    incidentsLast12m: 9,
    severeIncidents: 4,
    drillCoverage: 66,
    evacuationCompliance: 70,
    avgResponseMins: 15.1,
    vulnerableStudentsPct: 23,
    readinessScore: 74,
    readinessTrend: "down",
    lastAudit: "2026-03-08",
    source: "Regional Monsoon Risk Preparedness Report 2025",
  },
  {
    id: 7,
    institution: "Green Valley Public School",
    city: "Pune",
    hazard: "Lightning & Storm",
    incidentsLast12m: 5,
    severeIncidents: 1,
    drillCoverage: 81,
    evacuationCompliance: 84,
    avgResponseMins: 10.8,
    vulnerableStudentsPct: 13,
    readinessScore: 83,
    readinessTrend: "stable",
    lastAudit: "2026-03-05",
    source: "Lightning Safety Preparedness Brief 2025",
  },
  {
    id: 8,
    institution: "Starlight Senior Secondary",
    city: "Kolkata",
    hazard: "Cyclone & Waterlogging",
    incidentsLast12m: 6,
    severeIncidents: 2,
    drillCoverage: 79,
    evacuationCompliance: 81,
    avgResponseMins: 12.3,
    vulnerableStudentsPct: 17,
    readinessScore: 81,
    readinessTrend: "stable",
    lastAudit: "2026-03-11",
    source: "Coastal School Disaster Readiness Assessment 2025",
  },
];

export const monthlyRiskTrend = [
  { month: "Oct", risk: 58 },
  { month: "Nov", risk: 61 },
  { month: "Dec", risk: 55 },
  { month: "Jan", risk: 50 },
  { month: "Feb", risk: 47 },
  { month: "Mar", risk: 43 },
];

export const reportBasis = [
  "Hazard categories are aligned with recurring school-impact events seen in public disaster updates (flood, cyclone, heatwave, landslide, lightning).",
  "Response and evacuation indicators reflect preparedness metrics commonly used in school safety audits.",
  "Entries are realistic training references for planning and simulation, not official government incident logs.",
];
